### ISSUE TITLE
Meeting August 17h

### ISSUE THREAD

**Issue by krrisis** [aragon/aragondac-community#11]
Plz add your agenda topics in [this document](https://docs.google.com/document/d/1_dDu4ZVZiiIpO4cKb5tAiWJf8iMkBh157N7wlgXtvTo/edit?usp=sharing) or in the comments below

**Comment by mariapao** [comment]
@krrisis you mean August, right?

**Comment by krrisis** [comment]
@mariapao aaargh Mondays 🙈 #fixed! :)
