### ISSUE TITLE
Announcement Aragon DAC

### ISSUE THREAD

**Issue by krrisis** [aragon/aragondac-community#2]
Proposed timing 

- [x] briefing by @griffgreen
- [x] writing of first draft by @krrisis by 20/07
- [x] feedback on draft by Quazia Griff Chris Luke Tatu 24/07 EOD
- [x] Rewrite by @krrisis by 25/07 EOD 
- [x] second feedback integration by @krrisis by 26/07 EOD 
- [ ] Signoff by all by 27/07 EOD 
- [x] Publish post by Aragon on 30/07 by @john-light   
- [x] Sharing in communities by @john-light & @krrisis

**Comment by krrisis** [comment]
Meeting 1 notes as inspiration https://drive.google.com/open?id=1e1e4Y1kFoEsBk-drA333---Abb66sK6OyIaQx1BS2PI

**Comment by mariapao** [comment]
Kris, Tatu will get back from holidays the first week of August

**Comment by krrisis** [comment]
hey @mariapao  do you mean by that we'd better wait to publish until that moment or will someone else in the Aragon org take this over? Currently based myself on having the post ready by next week, when we'll probably receive the funds? Let me know!

**Comment by krrisis** [comment]
First 'draft' ready for your feedback, esp. @lkngtn @griffgreen @chris-remus @Quazia @Smokyish but others very welcome too ofc! https://docs.google.com/document/d/1Y1nLNlro2cCjjC-M6aRqFqpUtGwbwneQ_xQms5qM7Mk/edit?usp=sharing

**Comment by mariapao** [comment]
Hey @krrisis it was just to let you know, we don't have to wait for Tatu.

I received the second version of the legal agreement this afternoon. I'll review it and send it to Griff and Luis tonight or tomorrow morning. Once we close the agreement we send the funds so if everything goes smoothly I think next week you will be receiving the funds :)

**Comment by mariapao** [comment]
@GriffGreen I wasn't able to share the agreement over the weekend but [here]([url](https://docs.google.com/document/d/1XcKKNTN7EoQifWOKIBXwpbG8BYOZmILSuFr0HTkgozA/edit)) it is. Please review and comment :)

@krrisis  I need to have the basics of the "Building theAragonDAC" doc agreed and closed so we can include such doc and an Schedule. We have a new version of this doc, right? I see that there is no comments. I'm just making sure I have the right doc.

**Comment by krrisis** [comment]
Notes here https://docs.google.com/document/d/1sCrRP80ZmkDSKeEe9abLkK0cEeHdEFPmtUfJHrIPPHc/edit?usp=sharing

**Comment by Smokyish** [comment]
Any updates on this?

**Comment by krrisis** [comment]
Waiting for final version of logo, hope we'll receive it today

**Comment by john-light** [comment]
We can close this issue now, yeah?

**Comment by krrisis** [comment]
haha yup, was just doing this :)
