### ISSUE TITLE
Legal agreement Aragon DAC

### ISSUE THREAD

**Issue by krrisis** [aragon/aragondac-community#4]
- [x] Comment & review on first draft legal agreement by @mariapao 
- [x] Send to stakeholders for review/ok (date?) 
- [x] Signing of final legal agreement

**Comment by mariapao** [comment]
I received the first draft of the agreement from the layers yesterday and I reviewed and commented it on that same date and set it back to them.

Now I'm waiting for the second version that Luis has to review next week (on vacation right now) but I will share that version with Griff so he can start reviewing it as well.

**Comment by mariapao** [comment]
@GriffGreen I wasn't able to share the agreement over the weekend but [here](https://docs.google.com/document/d/1XcKKNTN7EoQifWOKIBXwpbG8BYOZmILSuFr0HTkgozA/edit) it is. Please review and comment :)

@krrisis  I need to have the basics of the "Building theAragonDAC" doc agreed and closed so we can include such doc as an schedule to the agreement. We have a new version of this doc, right? I see that there is no comments. I'm just making sure I have the right doc.

**Comment by krrisis** [comment]
hey @mariapao - right version is linked in issue #10 ! :)

**Comment by mariapao** [comment]
@krrisis and what's the difference with the doc linked in issue #5 ?

**Comment by krrisis** [comment]
@mariapao zero, it's the same doc! Just linked there as Chris recently added comments, so we might want to discuss these in our next meeting

**Comment by GriffGreen** [comment]
@Quazia did you say you would sign the agreement? I think you can even sign it as "Quazia" If you have trouble with that, I would sign it as well.

**Comment by Quazia** [comment]
Yeah I can sign whatever; I'll sign it with legal name if needed.

**Comment by krrisis** [comment]
Has been signed by Griff in the meantime (if I understood correctly) -- @mariapao  could you send it to me or attach the signed version so I can put it on our google drive? thx!

**Comment by krrisis** [comment]
Link to signed doc [here](https://drive.google.com/file/d/1pwVcd05T-57e1DjipT6bMHeFbZLNCE-t/view?usp=sharing)
